const DAY_MS = 24 * 3600 * 1000;

const formatDate = (offsetDays) => new Date(Date.now() - offsetDays * DAY_MS).toLocaleDateString();

export const baselineGovtStats = {
  totalKwh: 73620,
  totalListings: 128,
  activeListings: 31,
  registeredCount: 184,
};

export const simulatedProsumers = [
  {
    address: '0x7A9e2b5d8c14A307F6046c98C91e55761DaA0011',
    subsidyID: 'PMKUSUM-MP-1142',
    location: 'Bhopal, MP',
    feeder: 'BPL-11KV-07',
    meterId: 'SIM-MTR-001',
    capacityKw: '5.0',
    trustScore: 86,
    generated: 1840,
    credits: 1840,
    lastReading: formatDate(2),
    daysSilent: 2,
    lastKwh: 22,
    expectedKwh: 24,
    riskScore: 12,
    riskReason: 'Generation matches panel capacity and feeder profile',
    anomalyTags: ['verified meter', 'normal curve'],
    status: 'Healthy',
    source: 'Simulated',
  },
  {
    address: '0x2F41aCA9eD23530819f78c9C26d18D52dEaA0022',
    subsidyID: 'PMKUSUM-MP-2097',
    location: 'Indore, MP',
    feeder: 'IND-33KV-12',
    meterId: 'SIM-MTR-014',
    capacityKw: '3.5',
    trustScore: 78,
    generated: 1265,
    credits: 1265,
    lastReading: formatDate(1),
    daysSilent: 1,
    lastKwh: 15,
    expectedKwh: 17,
    riskScore: 18,
    riskReason: 'Normal generation curve',
    anomalyTags: ['normal curve'],
    status: 'Healthy',
    source: 'Simulated',
  },
  {
    address: '0xA31B4095D8764f7e510E28B936941F2E83aA0033',
    subsidyID: 'PMKUSUM-MP-3348',
    location: 'Gwalior, MP',
    feeder: 'GWL-11KV-03',
    meterId: 'SIM-MTR-029',
    capacityKw: '6.0',
    trustScore: 91,
    generated: 2688,
    credits: 2688,
    lastReading: formatDate(0),
    daysSilent: 0,
    lastKwh: 29,
    expectedKwh: 30,
    riskScore: 8,
    riskReason: 'Recent reading verified by local feeder telemetry',
    anomalyTags: ['verified meter', 'feeder match'],
    status: 'Healthy',
    source: 'Simulated',
  },
];

export const fraudScenarios = {
  spike: {
    label: 'Meter Spike',
    action: 'Hold carbon credits and dispatch meter audit',
    row: {
      address: '0xF1A90000000000000000000000000000000000A1',
      subsidyID: 'PMKUSUM-FRAUD-9001',
      location: 'Jabalpur, MP',
      feeder: 'JBL-11KV-21',
      meterId: 'SIM-MTR-091',
      capacityKw: '2.0',
      trustScore: 28,
      generated: 940,
      credits: 940,
      lastReading: formatDate(0),
      daysSilent: 0,
      lastKwh: 168,
      expectedKwh: 48,
      riskScore: 94,
      riskReason: 'Daily reading exceeds physical panel capacity',
      evidence: 'Claimed 168 kWh against a 48 kWh daily ceiling',
      anomalyTags: ['capacity breach', 'credit hold'],
      status: 'Fraud Risk',
      source: 'Simulated',
    },
  },
  silent: {
    label: 'Silent Meter',
    action: 'Apply inactivity check and freeze marketplace listing',
    row: {
      address: '0xF1A90000000000000000000000000000000000B2',
      subsidyID: 'PMKUSUM-FRAUD-8174',
      location: 'Ujjain, MP',
      feeder: 'UJN-33KV-04',
      meterId: 'SIM-MTR-072',
      capacityKw: '4.2',
      trustScore: 36,
      generated: 2105,
      credits: 2105,
      lastReading: formatDate(13),
      daysSilent: 13,
      lastKwh: 0,
      expectedKwh: 76,
      riskScore: 82,
      riskReason: 'No smart-meter reading inside the 7-day window',
      evidence: 'Meter has been silent for 13 days',
      anomalyTags: ['meter silent', 'listing freeze'],
      status: 'Fraud Risk',
      source: 'Simulated',
    },
  },
  duplicate: {
    label: 'Duplicate Subsidy',
    action: 'Reject approval until subsidy ownership is verified',
    row: {
      address: '0xF1A90000000000000000000000000000000000C3',
      subsidyID: 'PMKUSUM-MP-1142',
      location: 'Bhopal, MP',
      feeder: 'BPL-11KV-07',
      meterId: 'SIM-MTR-108',
      capacityKw: '5.0',
      trustScore: 22,
      generated: 0,
      credits: 0,
      lastReading: formatDate(0),
      daysSilent: 0,
      lastKwh: 0,
      expectedKwh: 24,
      riskScore: 88,
      riskReason: 'Subsidy ID already belongs to another wallet',
      evidence: 'Two addresses submitted the same subsidy ID',
      anomalyTags: ['duplicate subsidy', 'approval block'],
      status: 'Fraud Risk',
      source: 'Simulated',
    },
  },
};

export const simulatedPendingApprovals = [
  {
    address: '0xCd1B16E9F2191B74a2F49A7b2B078d7F1B120045',
    subsidyID: 'PMKUSUM-MP-5510',
    location: 'Sagar, MP',
    capacityKw: '4.8',
    source: 'Simulated',
  },
  {
    address: '0x93c3D19e80E77F72A6870865182663E2A0280062',
    subsidyID: 'PMKUSUM-MP-5510',
    location: 'Sagar, MP',
    capacityKw: '4.8',
    source: 'Simulated',
    risk: 'Duplicate subsidy check required',
  },
];

export function makeTelemetry(rows) {
  const atRisk = rows.filter((row) => row.status === 'Fraud Risk').length;
  const totalExpected = rows.reduce((sum, row) => sum + row.expectedKwh, 0);
  const totalObserved = rows.reduce((sum, row) => sum + row.lastKwh, 0);
  return {
    atRisk,
    monitored: rows.length,
    avgTrust: rows.length ? Math.round(rows.reduce((sum, row) => sum + row.trustScore, 0) / rows.length) : 0,
    variancePct: totalExpected ? Math.round(((totalObserved - totalExpected) / totalExpected) * 100) : 0,
  };
}
